name:                clphs
version:             0.1.0.0
github:              "totbwf/clphs"
license:             BSD3
author:              "Reed Mullanix"
maintainer:          "reedmullanix@gmail.com"
copyright:           "2018 Reed Mullanix"

extra-source-files:
- examples/*.hs
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/totbwf/clphs#readme>

dependencies:
- base >= 4.7 && < 5
- mtl >= 2 && < 3
- containers >= 0.5 && < 0.6

library:
  source-dirs: src

tests:
  clphs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - clphs
